# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zotio < Formula
  desc "Zotero automation CLI: local-first search, library health checks, preview-first writes, annotation export, and MCP"
  homepage "https://github.com/OrgMentem/zotio"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.1/zotio_0.1.1_darwin_amd64.tar.gz"
      sha256 "41a04f936c6c992fba140e96bcc46da7cb7084267a8a00b491771d4090c57784"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.1/zotio_0.1.1_darwin_arm64.tar.gz"
      sha256 "0edef62409f43bec61109c73855e5507ac99a9b1876fe23b8956fb568c2a6105"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.1/zotio_0.1.1_linux_amd64.tar.gz"
      sha256 "a30d51de941c24399645b2e4ada7271b7cdf3eac5e916b00e3b589a90140c3b5"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.1/zotio_0.1.1_linux_arm64.tar.gz"
      sha256 "b2e47e391f0cd0c8c105d946a7da175b64fcea5fc69b6feb384d409f8f8f6713"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end
end
