# This file was generated by GoReleaser. DO NOT EDIT.
cask "papio" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "86aef1d68b711a93064cb36c494e0db42daacbfb183fa2624951046c10192900"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47db56940f9f9b6e2625c97fa5bfe8c40ad26bebe311234728c402469c84dde6"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d5c5536f9c80d2520711326d5d8e40c2252b19cf4064720da2c55bf39baba21"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "11f41ec7d12b8ceb4454d88b8c9f277b7b1b21b14810ce06e33bd30fa52e5721"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "papio"
  desc "Autonomous scholarly-paper acquisition broker that files validated PDFs into Zotero via zotio"
  homepage "https://github.com/OrgMentem/papio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papio"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
