# This file was generated by GoReleaser. DO NOT EDIT.
cask "papio" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "782f6bc17a2c7784d9c462961453af3876810fc6c9de587e784b3ea97aba6980"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "131405f8a6ed3b0d910d73c861ac4c420613239381280345dd00fe4b565f5c34"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee91b2c911732373a9418e1ab288c979e1f70e18d9dece0f43a1e4a0de83462b"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de6d2a1df67306f07afc99b31403d6cc1cb26dfd0cc408877098e189af0a1d8a"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "papio"
  desc "Autonomous scholarly-paper acquisition broker that files validated PDFs into Zotero via zotio"
  homepage "https://github.com/OrgMentem/papio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papio"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
