# This file was generated by GoReleaser. DO NOT EDIT.
cask "papio" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "99daaaaf9454fc301a6eb8181a65ebd305a81b6b7c5892fef9de738bbfc302bc"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bacc2ef26bdbdd697ad45665d58c90614cbc51aef89237980447f04bd730a274"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "258338cf7f5be99036bd2dc693ab4e6d2f4d795143887165989ff172312d27c7"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd92aca2faf0876c291e30896b2bab6e9cbe66da75d7a9e103928d8057156710"
      url "https://github.com/OrgMentem/papio/releases/download/v#{version}/papio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "papio"
  desc "Autonomous scholarly-paper acquisition broker that files validated PDFs into Zotero via zotio"
  homepage "https://github.com/OrgMentem/papio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papio"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
