# This file was generated by GoReleaser. DO NOT EDIT.
cask "zotio" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "e305e7c57c0bf504a13cf5d0222c50afed80f97529774182b5e0b44e568ba61e"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02147edc1f5d732c0f47850d74243488e8dba2f9270c13758dac17d3cac278f6"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa0c0c5a635c4886dde28ff1ebd3437808ded7183123a39e587d36818619ee4f"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51267ba961ca5ce0b87b8d72fc2f2c244637942413ce46a10cd6bd0c7494a558"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zotio"
  desc "Zotero automation CLI: local-first search, library health checks, preview-first writes, annotation export, and MCP"
  homepage "https://github.com/OrgMentem/zotio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zotio"
  binary "zotio-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
