# This file was generated by GoReleaser. DO NOT EDIT.
cask "zotio" do
  version "0.24.0"

  on_macos do
    on_arm do
      sha256 "a52c6bdb32eaec2313ffe93b980fe231a08f98bb7c991fe620715195bd7dd743"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74987763bfed89efbb8c07256fa8738dc25cb626f7f7df3cac69e0069b684030"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "935e5020cdb5b17608c60e77a8889c781db921dc8e7d8b7563eb17a7ba92461f"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31dc663a2f06e1d5ab3a01ea07b74131a7867c4d5401eaf7241c1837575c5062"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "zotio"
  desc "Zotero library checks and automation: local-first search, CI health gates, preview-first writes, workflows, and MCP"
  homepage "https://github.com/OrgMentem/zotio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zotio"
  binary "zotio-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
