# This file was generated by GoReleaser. DO NOT EDIT.
cask "zotio" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "ae3de2dd931c93c819593a0949f4838a67b9f5b6283fe53c9cbaeb38e6dcbffc"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8d2f701713141334801c9cabadb9d0e0919cfff8ebbf0f55a761e8a6a694f34"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "431d939c577d0719eb76fed027116c8e125a8fbb796ada7d954efb7cfaf96be9"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04adacddc9789f79707b087c85022df8ea58ca0fca4b5c2d3704504e9afd2f7e"
      url "https://github.com/OrgMentem/zotio/releases/download/v#{version}/zotio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "zotio"
  desc "Zotero automation CLI: local-first search, library health checks, preview-first writes, annotation export, and MCP"
  homepage "https://github.com/OrgMentem/zotio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zotio"
  binary "zotio-mcp"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required

end
