# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zotio < Formula
  desc "Zotero automation CLI: local-first search, library health checks, preview-first writes, annotation export, and MCP"
  homepage "https://github.com/OrgMentem/zotio"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.2/zotio_0.1.2_darwin_amd64.tar.gz"
      sha256 "0e861f77f7041e2ea1dda898123943996961c1a9418efa9cf8c00aa1193ffd89"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.2/zotio_0.1.2_darwin_arm64.tar.gz"
      sha256 "d758f81ec9d1e2511a1fcd77ced280c6bbf2635e92b74e558b8a0d56fe0d60a8"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.2/zotio_0.1.2_linux_amd64.tar.gz"
      sha256 "1aa06e4ca517b1ffcb6924250c79e0a4e46ceaed5d6f50ac0a44a31f0be06a2b"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.1.2/zotio_0.1.2_linux_arm64.tar.gz"
      sha256 "1772d900ce02f978f88afc46f63ca6994cf91f0554aaee568f27e721f82ba46d"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end
end
