# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zotio < Formula
  desc "Zotero automation CLI: local-first search, library health checks, preview-first writes, annotation export, and MCP"
  homepage "https://github.com/OrgMentem/zotio"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.7.0/zotio_0.7.0_darwin_amd64.tar.gz"
      sha256 "93430e62554ece0fd8a93d8893c46e761933a57f2487790fe89a58a56c66b3bf"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.7.0/zotio_0.7.0_darwin_arm64.tar.gz"
      sha256 "75a024c1b6f91336c0cdba11c32d1cabc0b687d22b3dedd51dba6530b6498869"

      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.7.0/zotio_0.7.0_linux_amd64.tar.gz"
      sha256 "00311ccce000a34009bb85a51db431121260789d484aa672b583275d68896539"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OrgMentem/zotio/releases/download/v0.7.0/zotio_0.7.0_linux_arm64.tar.gz"
      sha256 "696d3f192524f31da7c19a5196797ff54967b10bfce9904bc9e2f1aad83dac6a"
      define_method(:install) do
        bin.install "zotio"
        bin.install "zotio-mcp"
      end
    end
  end
end
